version: '3'
services:

  #PHP Service
  php:
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: ${PROJECT_NAME}-php
    ports:
      - ${APACHE_PORT}:80
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: "client_host=${LOCALHOST} client_port=9003"
      PHP_IDE_CONFIG: "serverName=dev.localhost"
      PHP_ENABLE_XDEBUG: 1
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql
    container_name: ${PROJECT_NAME}-db
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge